# Settings for the book which can be called within the book source files
#
# in book/book.html.erb
#
#      <p><b>Version:</b> <%= book.epub.version %></p>
#
#   or
#
#      <% if book.epub.version == '1.0.0' %>
#        <p>Whew! We made it!</p>
#      <% end %>

title: Bookshop
subtitle: An HTML-to-PDF/(e)Book Publishing Framework
isbn: 1234567891011     # ISBN-13


# Place the pdf specific settings here. Use whatever you want.
# You can use these settings in your source layouts by using a tag
#   in book.html.erb you could use <%= book.pdf.title %>
pdf:
  version: 0.0.1
  title: Bookshop (PDF Version)


# Place the epub specific settings here.
epub:
  version: 0.0.1
  title: Bookshop ePub Version


# Place the html specific settings here
html:
  title: Bookshop HTML version


# You can add any additional variables you want
#
# foo:
#   bar: foobar
#
#   in book.html.erb you can then use <%= foo.bar %>  # --> foobar